config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :projects, only: :show

  match '/contacts', to: 'contacts#new', via: 'get'
  resources :contacts, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name, :validate => true
  attribute :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message, :validate => true
  attribute :nickname, :captcha  => true

  def headers
    {
      :subject => "New Contact from portfolio form",
      :to => "jad.portfolio@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/contact_form.rb
class ContactForm < MailForm::Base
  attribute :name, :validate => true
  attribute :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message, :validate => true
  attribute :nickname, :captcha  => true

  def headers
    {
      :subject => "New Contact From Portfolio Form",
      :to => "jessicaadewitt@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/project.rb
class Project < ApplicationRecord
  def img
    self.name.split.first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def default_url_options
  { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/contact_forms_controller.rb
class ContactFormsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
      redirect_to root_path, notice: 'Message successfully sent'
    else
      flash.now[:error] = 'Please fill in all fields before sending message'
      render :new
    end
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
     @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      # flash.now[:notice] = nil
      redirect_to root_path, notice: 'Message successfully sent'
    else
      flash.now[:error] = 'Please fill in all fields before sending message'
      render :new
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @projects = Project.all
    @contact = Contact.new
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def show
    @project = Project.find(params[:id])
    @num_of_images = @project.images.length
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/contacts/new.html.erb
<div class="section section-blue section-w-footer">
  <h2>Contact</h2>
  <p class="text-center">Feel free to connect with me using the form below or any of the links provided.</p>
  <div class="form-contact">
    <%= simple_form_for @contact do |f| %>
      <% if flash[:error].present? %>
        <p><%= flash[:error] %></p>
      <% end %>

      <div class="form-inputs">
        <div class="form-group w100 string required user_first_name">
          <input class="form-control string first_name required special w100" autocomplete="name" autofocus="autofocus" required="required" aria-required="true" placeholder="Full Name" type="text">
        </div>
        <div class="form-group w100 email required user_email">
          <input class="form-control string email required special w100" autocomplete="email" autofocus="autofocus" required="required" aria-required="true" placeholder="Email" type="email" value="">
        </div>
        <div class="form-group w100 required">
          <textarea class="form-control required special w100" autocomplete="email" autofocus="autofocus" required="required" aria-required="true" placeholder="Message" type="email" value="" id="user_email"></textarea>
        </div>

      <div class="hidden">
        <%= f.text_field :nickname, hint: 'leave this field blank' %>
      </div>

      <%= f.button :submit, 'Send Message', class: "btn-box btn-hover-white" %>
    <% end %>
  </div>
</div>
</div>
<div class="section-blue"><%= render "shared/footer" %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= favicon_link_tag %>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=EB+Garamond|Oswald:300,400,600">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>

    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="section home-landing">
  <div class="home-landing-words">
    <h1>Full Stack Developer</h1>
    <h1>Content Creator</h1>
    <h1>Freelancer</h1>
  </div>
</div>


<div class="section section-white" id="projects">
  <h2>Projects</h2>
  <p class="text-center">Click a project to find out more.</p>

  <div class="card-projects">
    <% @projects.each_with_index do |project, index| %>

      <div class="card-project img-hidden">
        <div class="card-project-details">
            <!-- Image and information for the card -->
            <%= image_tag project.images[0], alt: "image of project" %>
            <div class="card-project-description">
              <h4><%= project.name %></h4>
              <p><%= project.sentence %></p>
            </div>

            <!-- Overlayed link to projects show page -->
            <%= link_to project_path(project) do %>
              <div class="hid-link"></div>
            <% end %>
        </div>
      </div>

    <% end %>
  </div>

</div>


<div class="section section-blue" id="writing">
  <h2>Writing</h2>
  <div>

    <div class="card-writing">
      <div class="position-relative">
        <i class="fab fa-medium" aria-hidden="true"></i>
        <%= image_tag "Sustainable-Fashion.jpg", alt: "picture of Startup Grind gathering" %>
      </div>
      <div>
        <h4>Sustainable Fashion Starts Small</h4>
        <p>Description of a Startup Grind event on the fashion industry in Oslo. Both companies have unique and interesting methods of behaving sustainably.</p>
        <%= link_to "Read the article", "https://medium.com/startup-grind-oslo/sustainable-fashion-starts-small-6fc26f1b0fbd", class: "btn-box" %>
      </div>
    </div>

    <div class="card-writing">
      <div class="position-relative">
        <i class="fab fa-youtube-square" aria-hidden="true"></i>
        <%= image_tag "fringe-presentation.jpg", alt: "picture of Jessica presenting My Fringe Planner" %>
      </div>
      <div>
        <h4>MyFringePlanner Presentation</h4>
        <p>At the end of Le Wagon, I presented MyFringePlanner with the help of Dee to a large audience and demonstrated the key user journeys for our application.</p>
        <%= link_to "Watch the video", "https://www.youtube.com/watch?v=L9Pvj2iJ6po&list=LLCKHwQkBDzhHRKgcGbfL54Q&index=2&t=39m50s", class: "btn-box" %>
      </div>
    </div>

    <div class="card-writing">
      <div class="position-relative">
        <i class="fab fa-medium" aria-hidden="true"></i>
        <%= image_tag "ml-article.png", alt: "picture of alpacas sharing ideas" %>
      </div>
      <div>
        <h4>Millenials Improve Workplace Communication</h4>
        <p>While working for ManageLabs I learned a lot about workplace communication and how different team members can contribute or detract from clear communication. </p>
        <%= link_to "Read the article", "https://www.managelabs.com/library/how-millennials-have-improved-workplace-communication", class: "btn-box" %>
      </div>
    </div>

  </div>
</div>


<div class="section section-white" id="about">
  <h2>About</h2>
  <div class="home-about">
   <%= image_tag "jess-profile.jpg", alt: "profile picture of jessica", class: "home-profile" %>
   <div class="p-3">
     <p>I am an avid word nerd who is researching and writing her way deeper into the worlds of web development and business communication. My previous work history includes a lot of leadership and mentorship roles both in offices and out on campgrounds.</p>
     <p>On the weekends you are most likely to find me exploring the outdoors, playing board games, or swing dancing my way to happiness.</p>
    </div>
  </div>

  <div class="section-sub home-tools">
    <h3 class="mt-5">Favorite Tools</h3>
    <h4>Frontend</h4>
      <ul>
        <li><i class="fab fa-bootstrap"></i></li>
        <li><i class="fab fa-figma" title="Figma"></i></li>
        <li><i class="fab fa-html5" title="HTML5"></i></li>
        <li><i class="fab fa-js-square" title="Javascript ES6"></i></li>
        <li><i class="fab fa-sass" title="SCSS"></i></li>
      </ul>
    <h4>Other</h4>
      <ul>
        <li><i class="fab fa-adobe"></i></li>
        <li><i class="fab fa-github-square"></i></li>
        <li><i class="fab fa-mailchimp" title="MailChimp"></i></li>
        <li><i class="fab fa-slack" title="Slack"></i></li>
      </ul>
    <h4>Backend</h4>
      <ul>
        <li><i class="fab fa-git-square"></i></li>
        <li class="svg"><%= inline_svg_tag "heroku-logo.svg", alt: "Heroku logo" %></i></li>
        <li class="svg"><%= inline_svg_tag "postgresql-logo.svg", alt: "Postgresql logo" %></li>
        <li class="svg"><%= inline_svg_tag "ruby-logo.svg", alt: "Ruby logo" %></li>
        <li class="svg"><%= inline_svg_tag "rails-logo.svg", alt: "Rails logo" %></li>
      </ul>


    <!---missing sqlite, redux, jquery, and nokogiri from original--->
    </ul>
  </div>

  <div class="section-sub">
    <h3>Interests</h3>
    <ul class="home-interests">
      <li>
        <%= image_tag "icon-restaurant.png", alt: "Food Icon" %>
        <h5>Food</h5>
      </li>
      <li>
        <%= image_tag "icon-disco-ball.png", alt: "Dance Icon" %>
        <h5>Dance</h5>
      </li>
      <li>
        <%= image_tag "icon-camera.png", alt: "Camera Icon" %>
        <h5>Photography</h5>
      </li>
      <li>
        <%= image_tag "icon-poker.png", alt: "Game Icon" %>
        <h5>Games</h5>
      </li>
      <li>
        <%= image_tag "icon-backpack.png", alt: "Travel Icon" %>
        <h5>Travel</h5>
      </li>
    </ul>
  </div>
</div>


<div class="section section-blue" id="section-350">
  <div>
    <h2>Contact</h2>
    <div class="text-center">
      <p>Feel free to connect with me using any of the links provided.</p>
      <%= link_to "Contact Form", new_contact_path, class: "btn-box" %>
    </div>
  </div>
  <ul class="social-media-icons"><%= render "shared/social_media_icons" %></ul>
</div>


<div class="home-footer section-blue">
  <p>Website designed and coded with ❤️ by Jessica DeWitt</p>
  <p>Pink gradient icons made by <a href="https://www.flaticon.com/authors/iconixar" title="iconixar">iconixar</a> oFn <a href="https://www.flaticon.com/" title="Flaticon">Flaticon</a></p>
  <a href="https://iconscout.com/icons/ruby" target="_blank">Ruby Icon</a> by <a href="https://iconscout.com/contributors/vorillaz">Vorillaz</a> on <a href="https://iconscout.com">Iconscout</a>
  <p><a href="https://iconscout.com/icons/postgresql" target="_blank">Postgresql Icon</a> by <a href="https://iconscout.com/contributors/icons8">Icons8</a> on <a href="https://iconscout.com">Iconscout</a></p>
  <p><a href="https://iconscout.com/icons/heroku" target="_blank">Heroku Icon</a> by <a href="https://iconscout.com/contributors/icons8">Icons8</a> on <a href="https://iconscout.com">Iconscout</a></p>
</div>

app/views/projects/show.html.erb
<div class="section section-white section-w-footer">

  <div class="project-display mx-auto">
    <%= render "shared/carousel" %>
    <div class="project-links">
      <%= link_to "GH SOURCE CODE", @project.codelink, class: "btn-box" %>
      <%= link_to "DEPLOYED PAGE", @project.sitelink, class: "btn-box"  %>
    </div>
  </div>

  <div class="project-info mx-auto">
    <h1><%= @project.name %></h1>
    <div>
      <h5>The Idea</h5>
      <p><%= @project.idea %></p>
      <br>
      <h5>The Tools</h5>
      <p><%= @project.tools %></p>
    </div>
  </div>

</div>

<%= render "shared/footer" %>

app/views/shared/_carousel.html.erb
<!-- Carousel images using Bootstrap -->
<div id="carousel-example-1z" class="carousel slide m-4" data-ride="carousel" data-interval="false">

  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
    <% ind_counter = 1 %>
    <% (@num_of_images - 1).times do %>
      <li data-target="#carousel-example-1z" data-slide-to="<%= ind_counter %>"></li>
      <% ind_counter += 1 %>
    <% end %>
  </ol>

  <!-- Slide Wrappers -->
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%#= image_tag "url(" + @project.images.first + ")", alt: "screenshots of project", class: "d-block" %>
      <img src="<%= @project.images.first %>" alt="">
    </div>

    <% img_counter = 1 %>
    <%  (@num_of_images - 1).times do %>
      <div class="carousel-item">
        <img src="<%= @project.images[img_counter] %>" alt="">
        <%#= image_tag "url(" + @project.images[counter] + ")", alt: "screenshots of project", class: "d-block" %>
      </div>
      <% img_counter += 1 %>
    <% end %>
  </div>

  <!-- Left and right controls -->
  <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>

</div>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

app/views/shared/_footer.html.erb
<div class="footer">
  <ul class="social-media-icons footer-social-media-icons"><%= render "shared/social_media_icons" %></ul>
  <p>Website designed and coded with ❤️ by Jessica DeWitt</p>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-menu">
  <%= link_to "HOME", root_path %> |
  <%= link_to "PROJECTS", "/#projects"  %> |
  <%= link_to "WRITING", "/#writing"  %> |
  <%= link_to "ABOUT", "/#about" %> |
  <%= link_to "CONTACT", new_contact_path %>
</div>

app/views/shared/_social_media_icons.html.erb
  <li><a href="https://www.facebook.com/jessica.dewitt.779"><i class="fab fa-facebook" aria-hidden="true"></i></a></li>
  <li><a href="https://www.instagram.com/opalevanescence/"><i class="fab fa-instagram" aria-hidden="true"></i></a></li>
  <li><a href="https://www.linkedin.com/in/jessica-a-dewitt/"><i class="fab fa-linkedin" aria-hidden="true"></i></a></li>
  <li><a href="https://github.com/Opalevanescence"><i class="fab fa-github" aria-hidden="true"></i></a></li>

app/views/shared/_writing.html.erb
<h2>Writing</h2>
  <div>
    
  <div class="card-writing">
    <div class="position-relative">
        <%= render "shared/mbsvg" %>
        <%= image_tag "mb-article.png", alt: "picture from the article featuring a page from Metabase" %>
    </div>
    <div>
        <h4>Visualizing Data with Maps</h4>
        <p>Walkthrough for working with Metabase's map visualization option. One of the tutorials and how-tos I wrote for Metabase during our contract.</p>
        <%= link_to "Read the article", "https://www.metabase.com/blog/map-visualization/index.html", class: "btn-box" %>
    </div>
    </div>

    <div class="card-writing">
      <div class="position-relative">
        <i class="fab fa-medium" aria-hidden="true"></i>
        <%= image_tag "Sustainable-Fashion.jpg", alt: "picture of Startup Grind gathering" %>
      </div>
      <div>
        <h4>Sustainable Fashion Starts Small</h4>
        <p>Description of a Startup Grind event on the fashion industry in Oslo. Both companies have unique and interesting methods of behaving sustainably.</p>
        <%= link_to "Read the article", "https://medium.com/startup-grind-oslo/sustainable-fashion-starts-small-6fc26f1b0fbd", class: "btn-box" %>
      </div>
    </div>

    <div class="card-writing">
      <div class="position-relative">
        <i class="fab fa-youtube-square" aria-hidden="true"></i>
        <%= image_tag "fringe-presentation.jpg", alt: "picture of Jessica presenting My Fringe Planner" %>
      </div>
      <div>
        <h4>MyFringePlanner Presentation</h4>
        <p>At the end of Le Wagon, I presented MyFringePlanner with the help of Dee to a large audience and demonstrated the key user journeys for our application.</p>
        <%= link_to "Watch the video", "https://www.youtube.com/watch?v=L9Pvj2iJ6po&list=LLCKHwQkBDzhHRKgcGbfL54Q&index=2&t=39m50s", class: "btn-box" %>
      </div>
    </div>

    <div class="card-writing">
      <div class="position-relative">
        <i class="fab fa-medium" aria-hidden="true"></i>
        <%= image_tag "ml-article.png", alt: "picture of alpacas sharing ideas" %>
      </div>
      <div>
        <h4>Millenials Improve Workplace Communication</h4>
        <p>While working for ManageLabs I learned a lot about workplace communication and how different team members can contribute or detract from clear communication. </p>
        <%= link_to "Read the article", "https://www.managelabs.com/library/how-millennials-have-improved-workplace-communication", class: "btn-box" %>
      </div>
    </div>

  </div>